// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/blog_service.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmptyMessages struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyMessages) Reset()         { *m = EmptyMessages{} }
func (m *EmptyMessages) String() string { return proto.CompactTextString(m) }
func (*EmptyMessages) ProtoMessage()    {}
func (*EmptyMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_service_fbe3979ccbe49bed, []int{0}
}
func (m *EmptyMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyMessages.Unmarshal(m, b)
}
func (m *EmptyMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyMessages.Marshal(b, m, deterministic)
}
func (dst *EmptyMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyMessages.Merge(dst, src)
}
func (m *EmptyMessages) XXX_Size() int {
	return xxx_messageInfo_EmptyMessages.Size(m)
}
func (m *EmptyMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyMessages.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyMessages proto.InternalMessageInfo

type GetWeatherResponse struct {
	CityName             string        `protobuf:"bytes,1,opt,name=cityName,proto3" json:"cityName,omitempty"`
	MaxTemperature       []int32       `protobuf:"varint,2,rep,packed,name=maxTemperature,proto3" json:"maxTemperature,omitempty"`
	MinTemperature       []int32       `protobuf:"varint,3,rep,packed,name=minTemperature,proto3" json:"minTemperature,omitempty"`
	Date                 []string      `protobuf:"bytes,4,rep,name=date,proto3" json:"date,omitempty"`
	Week                 []string      `protobuf:"bytes,5,rep,name=week,proto3" json:"week,omitempty"`
	DayWeather           []*DayWeather `protobuf:"bytes,6,rep,name=dayWeather,proto3" json:"dayWeather,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetWeatherResponse) Reset()         { *m = GetWeatherResponse{} }
func (m *GetWeatherResponse) String() string { return proto.CompactTextString(m) }
func (*GetWeatherResponse) ProtoMessage()    {}
func (*GetWeatherResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_service_fbe3979ccbe49bed, []int{1}
}
func (m *GetWeatherResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWeatherResponse.Unmarshal(m, b)
}
func (m *GetWeatherResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWeatherResponse.Marshal(b, m, deterministic)
}
func (dst *GetWeatherResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWeatherResponse.Merge(dst, src)
}
func (m *GetWeatherResponse) XXX_Size() int {
	return xxx_messageInfo_GetWeatherResponse.Size(m)
}
func (m *GetWeatherResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWeatherResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWeatherResponse proto.InternalMessageInfo

func (m *GetWeatherResponse) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *GetWeatherResponse) GetMaxTemperature() []int32 {
	if m != nil {
		return m.MaxTemperature
	}
	return nil
}

func (m *GetWeatherResponse) GetMinTemperature() []int32 {
	if m != nil {
		return m.MinTemperature
	}
	return nil
}

func (m *GetWeatherResponse) GetDate() []string {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *GetWeatherResponse) GetWeek() []string {
	if m != nil {
		return m.Week
	}
	return nil
}

func (m *GetWeatherResponse) GetDayWeather() []*DayWeather {
	if m != nil {
		return m.DayWeather
	}
	return nil
}

type DayWeather struct {
	Date                 string   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	MaxTemperature       int32    `protobuf:"varint,2,opt,name=maxTemperature,proto3" json:"maxTemperature,omitempty"`
	MinTemperature       int32    `protobuf:"varint,3,opt,name=minTemperature,proto3" json:"minTemperature,omitempty"`
	Weather              string   `protobuf:"bytes,4,opt,name=weather,proto3" json:"weather,omitempty"`
	Week                 string   `protobuf:"bytes,5,opt,name=week,proto3" json:"week,omitempty"`
	Img                  string   `protobuf:"bytes,6,opt,name=img,proto3" json:"img,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DayWeather) Reset()         { *m = DayWeather{} }
func (m *DayWeather) String() string { return proto.CompactTextString(m) }
func (*DayWeather) ProtoMessage()    {}
func (*DayWeather) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_service_fbe3979ccbe49bed, []int{2}
}
func (m *DayWeather) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DayWeather.Unmarshal(m, b)
}
func (m *DayWeather) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DayWeather.Marshal(b, m, deterministic)
}
func (dst *DayWeather) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DayWeather.Merge(dst, src)
}
func (m *DayWeather) XXX_Size() int {
	return xxx_messageInfo_DayWeather.Size(m)
}
func (m *DayWeather) XXX_DiscardUnknown() {
	xxx_messageInfo_DayWeather.DiscardUnknown(m)
}

var xxx_messageInfo_DayWeather proto.InternalMessageInfo

func (m *DayWeather) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *DayWeather) GetMaxTemperature() int32 {
	if m != nil {
		return m.MaxTemperature
	}
	return 0
}

func (m *DayWeather) GetMinTemperature() int32 {
	if m != nil {
		return m.MinTemperature
	}
	return 0
}

func (m *DayWeather) GetWeather() string {
	if m != nil {
		return m.Weather
	}
	return ""
}

func (m *DayWeather) GetWeek() string {
	if m != nil {
		return m.Week
	}
	return ""
}

func (m *DayWeather) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

type Article struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CoverImg             string   `protobuf:"bytes,3,opt,name=coverImg,proto3" json:"coverImg,omitempty"`
	ReadCount            int32    `protobuf:"varint,4,opt,name=readCount,proto3" json:"readCount,omitempty"`
	FavouriteCount       int32    `protobuf:"varint,5,opt,name=favouriteCount,proto3" json:"favouriteCount,omitempty"`
	Abstract             string   `protobuf:"bytes,6,opt,name=abstract,proto3" json:"abstract,omitempty"`
	CommentCount         int32    `protobuf:"varint,7,opt,name=commentCount,proto3" json:"commentCount,omitempty"`
	FilePath             string   `protobuf:"bytes,8,opt,name=filePath,proto3" json:"filePath,omitempty"`
	CreatedAt            string   `protobuf:"bytes,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Tag                  string   `protobuf:"bytes,10,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_service_fbe3979ccbe49bed, []int{3}
}
func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (dst *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(dst, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Article) GetCoverImg() string {
	if m != nil {
		return m.CoverImg
	}
	return ""
}

func (m *Article) GetReadCount() int32 {
	if m != nil {
		return m.ReadCount
	}
	return 0
}

func (m *Article) GetFavouriteCount() int32 {
	if m != nil {
		return m.FavouriteCount
	}
	return 0
}

func (m *Article) GetAbstract() string {
	if m != nil {
		return m.Abstract
	}
	return ""
}

func (m *Article) GetCommentCount() int32 {
	if m != nil {
		return m.CommentCount
	}
	return 0
}

func (m *Article) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *Article) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Article) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type ListArticlesResponse struct {
	Articles             []*Article `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListArticlesResponse) Reset()         { *m = ListArticlesResponse{} }
func (m *ListArticlesResponse) String() string { return proto.CompactTextString(m) }
func (*ListArticlesResponse) ProtoMessage()    {}
func (*ListArticlesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_service_fbe3979ccbe49bed, []int{4}
}
func (m *ListArticlesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListArticlesResponse.Unmarshal(m, b)
}
func (m *ListArticlesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListArticlesResponse.Marshal(b, m, deterministic)
}
func (dst *ListArticlesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListArticlesResponse.Merge(dst, src)
}
func (m *ListArticlesResponse) XXX_Size() int {
	return xxx_messageInfo_ListArticlesResponse.Size(m)
}
func (m *ListArticlesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListArticlesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListArticlesResponse proto.InternalMessageInfo

func (m *ListArticlesResponse) GetArticles() []*Article {
	if m != nil {
		return m.Articles
	}
	return nil
}

type ListArticlesRequest struct {
	PageIndex            int32    `protobuf:"varint,1,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListArticlesRequest) Reset()         { *m = ListArticlesRequest{} }
func (m *ListArticlesRequest) String() string { return proto.CompactTextString(m) }
func (*ListArticlesRequest) ProtoMessage()    {}
func (*ListArticlesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_service_fbe3979ccbe49bed, []int{5}
}
func (m *ListArticlesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListArticlesRequest.Unmarshal(m, b)
}
func (m *ListArticlesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListArticlesRequest.Marshal(b, m, deterministic)
}
func (dst *ListArticlesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListArticlesRequest.Merge(dst, src)
}
func (m *ListArticlesRequest) XXX_Size() int {
	return xxx_messageInfo_ListArticlesRequest.Size(m)
}
func (m *ListArticlesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListArticlesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListArticlesRequest proto.InternalMessageInfo

func (m *ListArticlesRequest) GetPageIndex() int32 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *ListArticlesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func init() {
	proto.RegisterType((*EmptyMessages)(nil), "EmptyMessages")
	proto.RegisterType((*GetWeatherResponse)(nil), "GetWeatherResponse")
	proto.RegisterType((*DayWeather)(nil), "DayWeather")
	proto.RegisterType((*Article)(nil), "Article")
	proto.RegisterType((*ListArticlesResponse)(nil), "ListArticlesResponse")
	proto.RegisterType((*ListArticlesRequest)(nil), "ListArticlesRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlogServiceClient is the client API for BlogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlogServiceClient interface {
	GetWeather(ctx context.Context, in *EmptyMessages, opts ...grpc.CallOption) (*GetWeatherResponse, error)
	ListArticles(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ListArticlesResponse, error)
}

type blogServiceClient struct {
	cc *grpc.ClientConn
}

func NewBlogServiceClient(cc *grpc.ClientConn) BlogServiceClient {
	return &blogServiceClient{cc}
}

func (c *blogServiceClient) GetWeather(ctx context.Context, in *EmptyMessages, opts ...grpc.CallOption) (*GetWeatherResponse, error) {
	out := new(GetWeatherResponse)
	err := c.cc.Invoke(ctx, "/BlogService/GetWeather", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) ListArticles(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ListArticlesResponse, error) {
	out := new(ListArticlesResponse)
	err := c.cc.Invoke(ctx, "/BlogService/ListArticles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogServiceServer is the server API for BlogService service.
type BlogServiceServer interface {
	GetWeather(context.Context, *EmptyMessages) (*GetWeatherResponse, error)
	ListArticles(context.Context, *ListArticlesRequest) (*ListArticlesResponse, error)
}

func RegisterBlogServiceServer(s *grpc.Server, srv BlogServiceServer) {
	s.RegisterService(&_BlogService_serviceDesc, srv)
}

func _BlogService_GetWeather_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessages)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).GetWeather(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BlogService/GetWeather",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).GetWeather(ctx, req.(*EmptyMessages))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_ListArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).ListArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BlogService/ListArticles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).ListArticles(ctx, req.(*ListArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BlogService",
	HandlerType: (*BlogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWeather",
			Handler:    _BlogService_GetWeather_Handler,
		},
		{
			MethodName: "ListArticles",
			Handler:    _BlogService_ListArticles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/blog_service.proto",
}

func init() {
	proto.RegisterFile("proto/blog_service.proto", fileDescriptor_blog_service_fbe3979ccbe49bed)
}

var fileDescriptor_blog_service_fbe3979ccbe49bed = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0x93, 0xba, 0x49, 0xa6, 0xa5, 0x94, 0x6d, 0x90, 0x96, 0xa8, 0x87, 0xc8, 0x42, 0x28,
	0x12, 0xaa, 0x23, 0x95, 0x2b, 0x97, 0x16, 0x10, 0xaa, 0xf8, 0x95, 0x8b, 0x40, 0xe2, 0x82, 0x36,
	0xf6, 0xd4, 0x5d, 0x61, 0x7b, 0x8d, 0x77, 0x92, 0x36, 0x1c, 0x79, 0x05, 0xce, 0xbc, 0x03, 0xe2,
	0x55, 0x10, 0x6f, 0xc0, 0x83, 0xa0, 0xdd, 0x75, 0x9c, 0x04, 0x72, 0xe0, 0x94, 0xfd, 0xbe, 0x99,
	0xdd, 0xf9, 0xbe, 0xf1, 0x4c, 0x80, 0x97, 0x95, 0x22, 0x35, 0x9e, 0x64, 0x2a, 0xfd, 0xa0, 0xb1,
	0x9a, 0xc9, 0x18, 0x43, 0x4b, 0x0d, 0x0e, 0x53, 0xa5, 0xd2, 0x0c, 0xc7, 0xa2, 0x94, 0x63, 0x51,
	0x14, 0x8a, 0x04, 0x49, 0x55, 0x68, 0x17, 0x0d, 0x6e, 0xc2, 0x8d, 0x27, 0x79, 0x49, 0xf3, 0x17,
	0xa8, 0xb5, 0x48, 0x51, 0x07, 0xbf, 0x3c, 0x60, 0x4f, 0x91, 0xde, 0xa1, 0xa0, 0x4b, 0xac, 0x22,
	0xd4, 0xa5, 0x2a, 0x34, 0xb2, 0x01, 0x74, 0x63, 0x49, 0xf3, 0x97, 0x22, 0x47, 0xee, 0x0d, 0xbd,
	0x51, 0x2f, 0x6a, 0x30, 0xbb, 0x07, 0x7b, 0xb9, 0xb8, 0x7e, 0x83, 0x79, 0x89, 0x95, 0xa0, 0x69,
	0x85, 0xbc, 0x35, 0x6c, 0x8f, 0xfc, 0xe8, 0x2f, 0xd6, 0xe6, 0xc9, 0x62, 0x35, 0xaf, 0x5d, 0xe7,
	0xad, 0xb1, 0x8c, 0xc1, 0x56, 0x22, 0x08, 0xf9, 0xd6, 0xb0, 0x3d, 0xea, 0x45, 0xf6, 0x6c, 0xb8,
	0x2b, 0xc4, 0x8f, 0xdc, 0x77, 0x9c, 0x39, 0xb3, 0xfb, 0x00, 0x89, 0x98, 0xd7, 0x4a, 0xf9, 0xf6,
	0xb0, 0x3d, 0xda, 0x39, 0xde, 0x09, 0x1f, 0x37, 0x54, 0xb4, 0x12, 0x0e, 0xbe, 0x7b, 0x00, 0xcb,
	0x50, 0x53, 0xc3, 0x79, 0x71, 0x35, 0x36, 0xf9, 0xf0, 0xfe, 0xd3, 0x87, 0xb7, 0xc1, 0x07, 0x87,
	0xce, 0x55, 0x2d, 0x6e, 0xcb, 0x96, 0x59, 0xc0, 0x15, 0x37, 0x5e, 0xe3, 0x66, 0x1f, 0xda, 0x32,
	0x4f, 0xf9, 0xb6, 0xa5, 0xcc, 0x31, 0xf8, 0xd6, 0x82, 0xce, 0x49, 0x45, 0x32, 0xce, 0x90, 0xed,
	0x41, 0x4b, 0x26, 0x56, 0xad, 0x1f, 0xb5, 0x64, 0xc2, 0xfa, 0xe0, 0x93, 0xa4, 0xcc, 0x49, 0xec,
	0x45, 0x0e, 0xd8, 0xaf, 0xa4, 0x66, 0x58, 0x9d, 0xe5, 0xa9, 0xd5, 0x64, 0xbe, 0x52, 0x8d, 0xd9,
	0x21, 0xf4, 0x2a, 0x14, 0xc9, 0x23, 0x35, 0x2d, 0xc8, 0xea, 0xf1, 0xa3, 0x25, 0x61, 0x3c, 0x5d,
	0x88, 0x99, 0x9a, 0x56, 0x92, 0xd0, 0xa5, 0xf8, 0xce, 0xd3, 0x3a, 0x6b, 0x2a, 0x88, 0x89, 0xa6,
	0x4a, 0xc4, 0x54, 0x4b, 0x6d, 0x30, 0x0b, 0x60, 0x37, 0x56, 0x79, 0x8e, 0x05, 0xb9, 0x17, 0x3a,
	0xf6, 0x85, 0x35, 0xce, 0xdc, 0xbf, 0x90, 0x19, 0xbe, 0x16, 0x74, 0xc9, 0xbb, 0xee, 0xfe, 0x02,
	0x1b, 0x85, 0x71, 0x85, 0x82, 0x30, 0x39, 0x21, 0xde, 0xb3, 0xc1, 0x25, 0x61, 0xfa, 0x43, 0x22,
	0xe5, 0xe0, 0xfa, 0x43, 0x22, 0x0d, 0x1e, 0x42, 0xff, 0xb9, 0xd4, 0x54, 0xb7, 0x48, 0x37, 0xb3,
	0x7a, 0x17, 0xba, 0xa2, 0xe6, 0xb8, 0x67, 0xa7, 0xa2, 0x1b, 0xd6, 0x49, 0x51, 0x13, 0x09, 0x5e,
	0xc1, 0xc1, 0xfa, 0xed, 0x4f, 0x53, 0xd4, 0x64, 0x44, 0x94, 0x22, 0xc5, 0xb3, 0x22, 0xc1, 0xeb,
	0xba, 0xdf, 0x4b, 0xc2, 0xc8, 0x37, 0xe0, 0x5c, 0x7e, 0x5e, 0x0c, 0x47, 0x83, 0x8f, 0x7f, 0x78,
	0xb0, 0x73, 0x9a, 0xa9, 0xf4, 0xdc, 0xad, 0x1f, 0x7b, 0x06, 0xb0, 0x5c, 0x24, 0xb6, 0x17, 0xae,
	0xed, 0xd9, 0xe0, 0x20, 0xfc, 0x77, 0xcb, 0x02, 0xfe, 0xe5, 0xe7, 0xef, 0xaf, 0x2d, 0xc6, 0xf6,
	0xed, 0xb6, 0xa6, 0x48, 0x47, 0x8b, 0x89, 0x79, 0x0b, 0xbb, 0xab, 0x6a, 0x59, 0x3f, 0xdc, 0x20,
	0x7e, 0x70, 0x3b, 0xdc, 0xd4, 0x90, 0xe0, 0x8e, 0x7d, 0xf6, 0x80, 0xdd, 0xb2, 0xcf, 0x66, 0x52,
	0xd3, 0x51, 0xdd, 0x86, 0xd3, 0xce, 0x7b, 0xdf, 0xfe, 0x11, 0x4c, 0xb6, 0xed, 0xcf, 0x83, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x76, 0xc0, 0x70, 0xd9, 0x49, 0x04, 0x00, 0x00,
}
